apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: consul
data:
  server.json: |
    {
      "ca_file": "/var/run/secrets/consul/ca.pem",
      "cert_file": "/var/run/secrets/consul/consul.pem",
      "key_file": "/var/run/secrets/consul/consul-key.pem",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ports": {
        "dns" : -1,
        "http": -1,
        "https": 8443
      }
    }

