apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  replicas: 3
  template:
    metadata:
      labels:
        name: consul
        app: vault
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  name: consul
            weight: 100
      terminationGracePeriodSeconds: 10
      serviceAccountName: consul
      containers:
      - name: consul
        image: consul:latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: consul
              key: gossip-encryption-key
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "agent"
        - "-server"
        - "-bind=0.0.0.0"
        - "-advertise=$(POD_IP)"
        - "-client=0.0.0.0"
        - "-bootstrap-expect=3"
        - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
        - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
        - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
        - "-config-file=/consul/config/server.json"
        - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
        - "-data-dir=/consul/data"
        - "-disable-host-node-id" # Required for running on single node cluster
        volumeMounts:
        - name: data
          mountPath: /consul/data
        - name: config
          mountPath: /consul/config
        - name: tls
          mountPath: /var/run/secrets/consul/certs
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
        ports:
        - containerPort: 8300
          name: server-rpc
        - containerPort: 8301
          name: serf-lan
        - containerPort: 8302
          name: serf-wan
        - containerPort: 8443
          name: https-api
      volumes:
      - name: config
        configMap:
          name: consul
      - name: tls
        secret:
          secretName: consul
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
