apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-client
data:
  client.json: |
    {
      "ca_file": "/var/run/secrets/consul/ca.pem",
      "cert_file": "/var/run/secrets/consul/consul-client.pem",
      "key_file": "/var/run/secrets/consul/consul-client-key.pem",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ports": {
        "dns" : -1,
        "http": -1,
        "https": 8443
      }
    }
